### ISSUE TITLE
issue: 部署初始化失败

### ISSUE THREAD

**Issue by zhaolion** [lyc8503/UptimeFlare#13]
部署后网站似乎打不开，如图

<img width="776" alt="image" src="https://github.com/lyc8503/UptimeFlare/assets/10258416/8b5c9596-3c8b-4e02-984d-09ec9beb0cdf">

console 显示:

```
2_app-f7bfd027cc9448b7.js:23 TypeError: Cannot read properties of null (reading 'overallUp')
    at OverallStatus (index-8f7a2988780303ec.js:1:611)
    at Xh (framework-0c7baedefba6b077.js:9:60990)
    at x (framework-0c7baedefba6b077.js:9:119445)
    at Vk (framework-0c7baedefba6b077.js:9:99130)
    at framework-0c7baedefba6b077.js:9:98997
    at Jk (framework-0c7baedefba6b077.js:9:99004)
    at Ok (framework-0c7baedefba6b077.js:9:95760)
    at Fk (framework-0c7baedefba6b077.js:9:96149)
    at jg (framework-0c7baedefba6b077.js:9:44899)
    at framework-0c7baedefba6b077.js:9:93661
console.error @ _app-f7bfd027cc9448b7.js:23
_app-f7bfd027cc9448b7.js:23 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
console.error @ _app-f7bfd027cc9448b7.js:23
2_app-f7bfd027cc9448b7.js:23 TypeError: Cannot read properties of null (reading 'latency')
    at MonitorDetail (index-8f7a2988780303ec.js:1:122643)
    at Xh (framework-0c7baedefba6b077.js:9:60990)
    at x (framework-0c7baedefba6b077.js:9:119445)
    at Vk (framework-0c7baedefba6b077.js:9:99130)
    at framework-0c7baedefba6b077.js:9:98997
    at Jk (framework-0c7baedefba6b077.js:9:99004)
    at Ok (framework-0c7baedefba6b077.js:9:95760)
    at Fk (framework-0c7baedefba6b077.js:9:96149)
    at jg (framework-0c7baedefba6b077.js:9:44899)
    at framework-0c7baedefba6b077.js:9:93661
console.error @ _app-f7bfd027cc9448b7.js:23
_app-f7bfd027cc9448b7.js:23 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
console.error @ _app-f7bfd027cc9448b7.js:23
_app-f7bfd027cc9448b7.js:23 Error rendering page:  Error: Cancel rendering route
    at _ (main-a82dbdedafde9961.js:1:13174)
    at main-a82dbdedafde9961.js:1:13126
    at new Promise (<anonymous>)
    at doRender (main-a82dbdedafde9961.js:1:13103)
    at main-a82dbdedafde9961.js:1:11240
```

**Comment by lyc8503** [comment]
请进入 Cloudflare Dashboard 打开这个 worker, 进入 Logs 采集 `Real time logs`.
![image](https://github.com/lyc8503/UptimeFlare/assets/36782264/62ec0ca1-02b1-4730-8307-38c94fd90b84)

另外, 请去除敏感信息后, 附上你的 `uptime.config.ts`

**Comment by zhaolion** [comment]
@lyc8503 非常感谢你的回复，我尝试按照你的指引检查了，似乎没有实时日志，不确定发生什么报错，如果还需要额外的信息，可以继续引导我去提供

<img width="835" alt="image" src="https://github.com/lyc8503/UptimeFlare/assets/10258416/53412f20-6ea1-4f62-b762-77f52ee71b4a">


uptime.config.ts
```
const pageConfig = {
  // Title for your status page
  title: "zhaolion's Status Page",
  // Links shown at the header of your status page, could set `highlight` to `true`
  links: [
    { link: 'https://xxx.com', label: 'Work' },
  ],
}

const workerConfig = {
  // Write KV at most every 3 minutes unless the status changed.
  kvWriteCooldownMinutes: 3,
  // Define all your monitors here
  monitors: [
    // Example HTTP Monitor
    {
      // `id` should be unique, history will be kept if the `id` remains constant
      id: 'zhaolion_monitor_google',
      // `name` is used at status page and callback message
      name: 'Google Web Monitor',
      // `method` should be a valid HTTP Method
      method: 'GET',
      // `target` is a valid URL
      target: 'https://www.google.com',
      // [OPTIONAL] `tooltip` is ONLY used at status page to show a tooltip
      tooltip: "google's monitor",
      // [OPTIONAL] `statusPageLink` is ONLY used for clickable link at status page
      statusPageLink: 'https://up.zhaolion.dev',
      // [OPTIONAL] `expectedCodes` is an array of acceptable HTTP response codes, if not specified, default to 2xx
      expectedCodes: [200],
      // [OPTIONAL] `timeout` in millisecond, if not specified, default to 10000
      timeout: 10000,
      // [OPTIONAL] headers to be sent
      headers: {
        'User-Agent': 'Uptimeflare',
        // Authorization: 'Bearer YOUR_TOKEN_HERE',
      },
      // [OPTIONAL] body to be sent
      body: 'Hello, world!',
      // [OPTIONAL] if specified, the response must contains the keyword to be considered as operational.
      responseKeyword: '',
      // [OPTIONAL] if specified, the check will run in your specified region,
      // refer to docs https://github.com/lyc8503/UptimeFlare/wiki/Geo-specific-checks-setup before setting this value
      checkLocationWorkerRoute: '',
    },
    // // Example TCP Monitor
    // {
    //   id: 'test_tcp_monitor',
    //   name: 'Example TCP Monitor',
    //   // `method` should be `TCP_PING` for tcp monitors
    //   method: 'TCP_PING',
    //   // `target` should be `host:port` for tcp monitors
    //   target: '1.2.3.4:22',
    //   tooltip: 'My production server SSH',
    //   statusPageLink: 'https://example.com',
    //   timeout: 5000,
    // },
  ],
  callbacks: {
    onStatusChange: async (
      env: any,
      monitor: any,
      isUp: boolean,
      timeIncidentStart: number,
      timeNow: number,
      reason: string
    ) => {
      // This callback will be called when there's a status change for any monitor
      // Write any Typescript code here

      // By default, this sends Bark and Telegram notification on every status change if you setup Cloudflare env variables correctly.
      await notify(env, monitor, isUp, timeIncidentStart, timeNow, reason)
    },
    onIncident: async (
      env: any,
      monitor: any,
      timeIncidentStart: number,
      timeNow: number,
      reason: string
    ) => {
      // This callback will be called EVERY 1 MINTUE if there's an on-going incident for any monitor
      // Write any Typescript code here
    },
  },
}

// Below is code for sending Telegram & Bark notification
// You can safely ignore them
const escapeMarkdown = (text: string) => {
  return text.replace(/[_*[\](){}~`>#+\-=|.!\\]/g, '\\$&');
};

async function notify(
  env: any,
  monitor: any,
  isUp: boolean,
  timeIncidentStart: number,
  timeNow: number,
  reason: string,
) {
  const dateFormatter = new Intl.DateTimeFormat('en-US', {
    month: 'numeric',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
    timeZone: 'Asia/Shanghai',
  });

  let downtimeDuration = Math.round((timeNow - timeIncidentStart) / 60);
  const timeIncidentStartFormatted = dateFormatter.format(new Date(timeIncidentStart * 1000));
  let statusText = isUp
    ? `The service is up again after being down for ${downtimeDuration} minutes.`
    : `Service became unavailable at ${timeIncidentStartFormatted}. Issue: ${reason || 'unspecified'}`;

  console.log('Notifying: ', monitor.name, statusText);

  if (env.BARK_SERVER && env.BARK_DEVICE_KEY) {
    try {
      let title = isUp ? `✅ ${monitor.name} is up again!` : `🔴 ${monitor.name} is currently down.`;
      await sendBarkNotification(env, monitor, title, statusText);
    } catch (error) {
      console.error('Error sending Bark notification:', error);
    }
  }

  if (env.SECRET_TELEGRAM_CHAT_ID && env.SECRET_TELEGRAM_API_TOKEN) {
    try {
      let operationalLabel = isUp ? 'Up' : 'Down';
      let statusEmoji = isUp ? '✅' : '🔴';
      let telegramText = `*${escapeMarkdown(
        monitor.name,
      )}* is currently *${operationalLabel}*\n${statusEmoji} ${escapeMarkdown(statusText)}`;
      await notifyTelegram(env, monitor, isUp, telegramText);
    } catch (error) {
      console.error('Error sending Telegram notification:', error);
    }
  }
}

export async function notifyTelegram(env: any, monitor: any, operational: boolean, text: string) {
  const chatId = env.SECRET_TELEGRAM_CHAT_ID;
  const apiToken = env.SECRET_TELEGRAM_API_TOKEN;

  const payload = new URLSearchParams({
    chat_id: chatId,
    parse_mode: 'MarkdownV2',
    text: text,
  });

  try {
    const response = await fetch(`https://api.telegram.org/bot${apiToken}/sendMessage`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: payload.toString(),
    });

    if (!response.ok) {
      console.error(
        `Failed to send Telegram notification "${text}",  ${response.status} ${response.statusText
        } ${await response.text()}`,
      );
    }
  } catch (error) {
    console.error('Error sending Telegram notification:', error);
  }
}

async function sendBarkNotification(env: any, monitor: any, title: string, body: string, group: string = '') {
  const barkServer = env.BARK_SERVER;
  const barkDeviceKey = env.BARK_DEVICE_KEY;
  const barkUrl = `${barkServer}/push`;
  const data = {
    title: title,
    body: body,
    group: group,
    url: monitor.url,
    device_key: barkDeviceKey,
  };

  const response = await fetch(barkUrl, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(data),
  });

  if (response.ok) {
    console.log('Bark notification sent successfully.');
  } else {
    const respText = await response.text();
    console.error('Failed to send Bark notification:', response.status, response.statusText, respText);
  }
}

// Don't forget this, otherwise compilation fails.
export { pageConfig, workerConfig }
```

**Comment by zhaolion** [comment]
我在 Actions 找到一些似乎有报错， 不确定对于定位问题是否有帮助，我贴在下面。

<img width="1163" alt="image" src="https://github.com/lyc8503/UptimeFlare/assets/10258416/9c61f5e7-1db1-41c9-bd00-6d49d040493f">

```
Plan: 4 to add, 0 to change, 0 to destroy.
cloudflare_workers_kv_namespace.uptimeflare_kv: Creating...
╷
│ Error: error creating workers kv namespace: create namespace: 'a namespace with this account ID and title already exists' (10014)
│ 
│   with cloudflare_workers_kv_namespace.uptimeflare_kv,
│   on deploy.tf line 19, in resource "cloudflare_workers_kv_namespace" "uptimeflare_kv":
│   19: resource "cloudflare_workers_kv_namespace" "uptimeflare_kv" {
│ 
╵
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```

**Comment by lyc8503** [comment]
感谢你提供的信息，看起来是第一次部署时遇到了问题，如果配置文件中没有敏感凭据的话，能否方便将仓库设置为公开，我可以查看一下你的 Actions 运行记录。

如果不方便公开的，请找到第一次部署成功的 Actions，贴出其中 ` Deploy using Terraform` 步骤的日志。

**Comment by DeemBear** [comment]
这是因为只是设置了CLOUDFLARE_API_TOKEN
CLOUDFLARE_ACCOUNT_ID没有设置，码主没提这个，要看deploy.yml，不设置CLOUDFLARE_ACCOUNT_ID也不知道是哪个CLOUDFLARE账号

**Comment by lyc8503** [comment]
> 这是因为只是设置了CLOUDFLARE_API_TOKEN
> CLOUDFLARE_ACCOUNT_ID没有设置，码主没提这个，要看deploy.yml，不设置CLOUDFLARE_ACCOUNT_ID也不知道是哪个CLOUDFLARE账号

deploy.yml 中会根据设置的 API Token 自动获取 Account ID, 如果你需要手动覆盖该设定, 才需要指定
CLOUDFLARE_ACCOUNT_ID 变量.

如果你觉得这步骤有问题, 请提供 Terraform 部署的报错日志以便排查, 谢谢.


DeemBear ***@***.***> 于2024年5月12日周日 10:55写道：

**Comment by zhaolion** [comment]
> 感谢你提供的信息，看起来是第一次部署时遇到了问题，如果配置文件中没有敏感凭据的话，能否方便将仓库设置为公开，我可以查看一下你的 Actions 运行记录。
> 
> 如果不方便公开的，请找到第一次部署成功的 Actions，贴出其中 ` Deploy using Terraform` 步骤的日志。

感谢你的回复，我这个项目暂时是没什么敏感信息的，我已经设置为 public，请继续帮忙看看问题在哪里

**Comment by lyc8503** [comment]
是 Terraform 部署失败了, 实际报错如下:
```
Plan: 4 to add, 0 to change, 0 to destroy.
cloudflare_workers_kv_namespace.uptimeflare_kv: Creating...
cloudflare_workers_kv_namespace.uptimeflare_kv: Creation complete after 0s [id=082bb56a9642436cae77ce820d3ef767]
cloudflare_pages_project.uptimeflare: Creating...
cloudflare_worker_script.uptimeflare: Creating...
cloudflare_worker_script.uptimeflare: Creation complete after 2s [id=uptimeflare_worker]
cloudflare_worker_cron_trigger.uptimeflare_worker_cron: Creating...
cloudflare_pages_project.uptimeflare: Creation complete after 3s [id=uptimeflare]
╷
│ Error: failed to update Worker Cron Trigger: workers.api.error.subdomain_required (10063)
│ 
│   with cloudflare_worker_cron_trigger.uptimeflare_worker_cron,
│   on deploy.tf line 37, in resource "cloudflare_worker_cron_trigger" "uptimeflare_worker_cron":
│   37: resource "cloudflare_worker_cron_trigger" "uptimeflare_worker_cron" {
│ 
╵
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```

错误原因是 `workers.api.error.subdomain_required`, 我之前也没见过这个错误, Cloudflare 文档中似乎也没有说明, 我再排查一下.

**Comment by lyc8503** [comment]
我可以在一个刚注册的全新的 Cloudflare 账号上复现这个问题, 但不能在我自己使用的账号上复现...

edit: 我只要在新账号上部署过一次, 再删除 Worker, 再重新创建就又可以了... 你使用的是之前从来没有创建过 Worker 的账号吗?

**Comment by lyc8503** [comment]
明白了, 从未创建过 Workers 的 Cloudflare 账号没有 Worker Domain, 导致新创建的 Worker 无法得到 subdomain, 导致 CRON 部署失败.

我稍后想办法解决这一问题.

**Comment by zhaolion** [comment]
> 我可以在一个刚注册的全新的 Cloudflare 账号上复现这个问题, 但不能在我自己使用的账号上复现...
> 
> edit: 我只要在新账号上部署过一次, 再删除 Worker, 再重新创建就又可以了... 你使用的是之前从来没有创建过 Worker 的账号吗?

对的，我第一次想尝试一下 workers，然后就这样了 😢

**Comment by zhaolion** [comment]
> 明白了, 从未创建过 Workers 的 Cloudflare 账号没有 Worker Domain, 导致新创建的 Worker 无法得到 subdomain, 导致 CRON 部署失败.
> 
> 我稍后想办法解决这一问题.

辛苦处理这个问题，我安静等待更新和重试一下 👍

**Comment by lyc8503** [comment]
这个问题只会在一个账号的第一次部署时出现, 所以其实你现在只要重新尝试下部署应该就能解决问题了😂

现在, 你需要先打开 https://dash.cloudflare.com/redirect?account=workers/kv/namespaces, 删除其中的 KV

然后再打开 https://dash.cloudflare.com/redirect?account=workers-and-pages 删除两个 uptimeflare 打头的 project

然后在 GitHub 这边重新修改下配置文件 (或者手动重新运行下 Actions) 应该就没问题了.

至于这个部署失败的问题, 似乎是由 Cloudflare API 诡异行为导致的, 应该算是上游的问题, 我在看有没有什么 Workaround.

附一份错误日志: 
[0_build-and-deploy.txt](https://github.com/lyc8503/UptimeFlare/files/15298409/0_build-and-deploy.txt)

**Comment by zhaolion** [comment]
> 这个问题只会在一个账号的第一次部署时出现, 所以其实你现在只要重新尝试下部署应该就能解决问题了😂
> 
> 现在, 你需要先打开 https://dash.cloudflare.com/redirect?account=workers/kv/namespaces, 删除其中的 KV
> 
> 然后再打开 https://dash.cloudflare.com/redirect?account=workers-and-pages 删除两个 uptimeflare 打头的 project
> 
> 然后在 GitHub 这边重新修改下配置文件 (或者手动重新运行下 Actions) 应该就没问题了.
> 
> 至于这个部署失败的问题, 似乎是由 Cloudflare API 诡异行为导致的, 应该算是上游的问题, 我在看有没有什么 Workaround.
> 
> 附一份错误日志: [0_build-and-deploy.txt](https://github.com/lyc8503/UptimeFlare/files/15298409/0_build-and-deploy.txt)

确实有点 tricky，但是新用户应该必现，朋友也遇到类似的情况了。我删除了相关项目后，重新运行部署成功了。最后非常感谢相关帮助🙏

**Comment by lyc8503** [comment]
暂时先 Reopen，等修复后再 close

**Comment by lyc8503** [comment]
已经修复，新用户不会遇到这个问题了，十分感谢你指出的问题！
